version: '3'
services:
  mysql:
   image: mysql:5.7
   command: --default-authentication-plugin=mysql_native_password
   environment:
    MYSQL_DATABASE: test
    MYSQL_ROOT_PASSWORD: hellokoding
    MYSQL_ROOT_HOST: '%'
   ports:
   - 3306:3306
   restart: always
   volumes:
     - /data/mysql1
  spring-boot-jpa-app:
    image: spring-boot-jpa-image
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysql
    ports:
      - 8081:8080
    volumes:
      - /data/spring-boot-app
